### PR TITLE
Credits

### PR DESCRIPTION
**Pull request by zMigueel**
Giving all of the credits for Gorillas-Team and my discord bot, Codya

### CODE REVIEW

**Comment by zMigueel** [comment]
Again requesting the credits because it is extremely ridiculous for your bot to have an absurd growth with our code and still insist on not giving any credit.

**Comment by Psykka** [comment]
if you do not give credit, we will resort to legal means, even if the code is modified it is still our organization's code.

**Comment by zMigueel** [comment]
Closes #4

**Comment by MrGamingBR** [comment]
Wait please...

**Comment by MrGamingBR** [comment]
Resolved.

**Pull request closed without merging**
